# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2014-2017 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

version: '2.3'

  # Services needed for inspirehep to run.
  redis:
    image: redis:3.2.3
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"
    ports:
      - "6379:6379"

  indexer:
    extends:
      file: services.yml
      service: indexer
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP="true"
    volumes:
      - "${DOCKER_DATA}/tmp/scoap3_elastic/data:/usr/share/elasticsearch/data"
      - "${DOCKER_DATA}/tmp/scoap3_elastic/log:/usr/share/elasticsearch/log"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      start_period: 15s
      test:
        - "CMD-SHELL"
        - "curl http://localhost:9200/_cluster/health | grep '.status.:.\\(green\\|yellow\\)'"

  rabbitmq:
    image: rabbitmq
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
    ports:
      - "15672:15672"
      - "5672:5672"

  database:
    extends:
      file: services.yml
      service: database
    volumes:
      - "${DOCKER_DATA}/tmp/scoap3_db/data:/var/lib/postgresql/data/pgdata"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "pg_isready --dbname=scoap3 --host=localhost --username=scoap3"